### PR TITLE
added conversion support,

### PR DESCRIPTION
**Pull request by thyngster**
ignore referrals
content grouping
Attribution overriding

### CODE REVIEW

**Comment by nicolasfranz** [comment]
Dear David, how are you doing? Allow me to ask you a few things. But first: thank you for your script, it works really well to make AMP compatible with GA4.

1. First, I'm not sure if I should be asking anything through this thread, but it seems to be the only one related to Conversions. Let me know if I should sharing my comments in any other branch/link/channel.
2. Well, I'm having some complications while trying to measure Conversions. Basically I need that some Events in GA4 could be marked as Conversions. But this is not happening at all.. I'm not sure if this is an issue with GA4 (a  bug) or if I should be adding anything to the script you have shared with the community. Can you please give point me to the right direction? In case you need any information, just let me know. Thank you!

**Comment by thyngster** [comment]
You can check the Conversion section on the README, here it explains how to set conversions.

**Comment by thyngster** [comment]
Adding, the following to the events that you want to mark as conversions should work:

```
"extraUrlParams": {
    "is_conversion": "1"
}
```

**Comment by nicolasfranz** [comment]
@thyngster thank you! It worked perfectly: check it out https://markuphero.com/share/l2fTr5fFaUuul3PJrYBP
Now I'm going to try to setup the other conversions.

**Comment by nicolasfranz** [comment]
Dear David, well, good news! I've been able to add the conversions Clicks and Scrolls, that's now working perfectly, check it out: 

`<script type="application/json">
{
    "vars": {
                "GA4_MEASUREMENT_ID": "xxxxxxx",
                "GA4_ENDPOINT_HOSTNAME": "www.google-analytics.com",
                "DEFAULT_PAGEVIEW_ENABLED": true,    
                "GOOGLE_CONSENT_ENABLED": false,
                "WEBVITALS_TRACKING": false,
                "PERFORMANCE_TIMING_TRACKING": false,
                "SEND_DOUBLECLICK_BEACON": false,
                "ENHANCED_MEASUREMENT_SCROLL": true
    },
	"extraUrlParams": {
		 "is_conversion": "1"
	},
	"triggers": {
		"videoPlayEvent": {
			"on": "video-ended",
			"request": "ga4Event",
			"vars": {
				"ga4_event_name": "video_finished"
			},
			"selector": ".video",
			"videoSpec": {},
			"extraUrlParams": {
				"event__str_video_title": "${id}",
				"event__num_video_duration": "${duration}"
			}
		},
		"mailtos": {
			"on": "click",
			"selector": ".bookdemo",
			"request": "ga4Event",
			"vars": {
			  "ga4_event_name": "demo_request_click"
		}
	  }
	} 
}
</script>
</amp-analytics> 
`
Here the result: https://markuphero.com/share/PJtB1RjhYq7sRFG6ruxb - working perfect!
I have just a few questions regarding two conversion that I want to improve:

- The scroll conversion, it seems like it only activates - according to your documentation - on 90% scroll, right? Is it possible to activate the event on 70%?
- I have a newsletter submission form at the bottom of my page, and I would like to measure the conversion after submit with an http 200 status response (considering the form is working with ajax, and not refreshing nor redirecting to any new URL after the submission). Then, what type of variable should I use to measure the conversion in this kind of situation?

Thank you for any lights you could bring to solve these last two issues.

**Comment by thyngster** [comment]
Hello @nicolasfranz, I appreciate your engagement with the project. I wanted to clarify the purpose of the issues section on GitHub. Its primary objective is to address genuine bugs, suggest improvements, and facilitate technical discussions related to the project.

However, it's important to note that the issues section is not intended for seeking free support or requesting others to complete your work. We encourage you to utilize the resources available, such as documentation and community support , to troubleshoot and find solutions to your technical questions.

If you have encountered any specific technical issues, please provide detailed information, and I will be more than happy to assist you in the right direction.

Thank you for your understanding and cooperation in adhering to the intended usage of the GitHub issues section.

**Comment by nicolasfranz** [comment]
Fully understood, thanks a lot @thyngster for your orientation!

**Pull request merged**
